excluded:
  - Carthage
  - Pods
  - .bundle

disabled_rules:
  - force_cast
  - force_try
  - unused_closure_parameter # 使用していないクロージャの引数を`_`にせず残したい
  - unused_optional_binding # 不必要にコード内にnilと書きたくない。またリリースビルドであれば最適化によってパフォーマンスに差は出ない
  - unused_capture_list # 元からXcodeがwarningを出してくれる
  - valid_docs
  - superfluous_disable_command
  - xctfail_message # 失敗理由が自明ならメッセージ不要

  # opt_in_rulesの中で無効にするルール
  - conditional_returns_on_newline # guard文は1行で書く場合がある
  - discouraged_object_literal # UIImageやUIColorのリテラル表記は使用する
  - discouraged_optional_collection # UIKitのメソッドで引っかかって煩わしい
  - empty_xctest_method
  - explicit_acl # internalは省略したい
  - explicit_enum_raw_value # raw valueは省略しても問題ない
  - explicit_top_level_acl # internalは省略したい
  - explicit_type_interface # 型推論を利用したい
  - extension_access_modifier # no_extension_access_modifierを優先する
  - fatal_error_message # fatal error message は省略して問題ない
  - file_header # 特に決まりが無い
  - file_name # protocolと実装クラスを同一ファイルに定義する場合がある
  - file_types_order # 厳しすぎる
  - force_unwrapping # 場合によって使用することがある
  - implicitly_unwrapped_optional # 場合によって使用することがある
  - no_grouping_extension # protocolにconfirmするコードはextensionに切り出す
  - prefixed_toplevel_constant # スコープによるprefixは不要な
  - required_enum_case # case数が少ないことは有り得る
  - switch_case_on_newline # 単に関数の戻り値をreturnする場合などは、単一行で書きたい
  - trailing_closure # sucscribe(onNext:)など省略可能なクロージャの引数が複数ある場合うまく機能しない
  - strict_fileprivate # fileprivate使うこともある
  - prohibited_interface_builder # IB使用する
  - multiline_arguments_brackets
  - multiline_parameters_brackets
  - missing_docs
  - nslocalizedstring_key
  - object_literal # リテラルではないイニシャライザも使う
  - required_deinit # deinitを毎回定義する必要性はない
  - strong_iboutlet # `@IBOutlet` はweakで良い
  - vertical_whitespace_between_cases # 各case間にEmpty lineは不要
  - xct_specific_matcher # `Bool?` に対して `XCTAssertTrue` できず不便
  - type_contents_order # 厳しすぎる
  - unowned_variable_capture # unowned使うこともある
  - indentation_width # 引数毎に改行した場合は、indent幅は固定にならない

opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_init
  - explicit_self
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - file_name_no_space
  - file_types_order
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - ibinspectable_in_extension
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - indentation_width
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - no_extension_access_modifier
  - no_grouping_extension
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_deinit
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

type_name:
  min_length:
    warning: 2
  max_length:
    warning: 45
    error: 60
  excluded:
    - X # coordinator
    - Y # coordinator

identifier_name:
  min_length:
    warning: 1
  allowed_symbols: [_] # private変数のprefixに"_"を付けることを許容するため
  validates_start_with_lowercase: false # private変数のprefixに"_"を付けることを許容するため

cyclomatic_complexity:
  warning: 10
  error: 15
  ignores_case_statements: true # Reducerの定義上、Actionに応じてswitchで分岐していくので、switchは計算しない

file_length:
  warning: 500
  error: 800

line_length:
  warning: 200
  error: 300
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

type_body_length:
  warning: 500

function_body_length:
  warning: 50

trailing_comma:
  # リテラル表記を要素毎に改行している場合、最後の要素に必ずcommaを付ける
  mandatory_comma: true

overridden_super_call:
  excluded:
    - setUp()
    - tearDown()